/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comecocos;

import data.Fantasmas;
import data.Figura;
import data.Mueve;
import data.Rejilla;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Toni
 */
public class ComecocosFrame extends javax.swing.JFrame {

    private Figura comecocos;
    private int vidas;
    
    private final int nFantasmas = 4;
    private Figura[] fantasmas = new Figura[nFantasmas];
    private final Rejilla rejilla;
    private boolean azules = false;
    private Timer timer = new Timer();
    
    private Mueve mueve;
    /**
     * Creates new form ComecocosFrame
     */
    public ComecocosFrame() {
        initComponents();
        this.rejilla = new Rejilla(this);
        this.init();
        vidas = 3;
        
        vida1.setVisible(true);
        vida2.setVisible(true);
        vida3.setVisible(true);
        gameover.setVisible(false);
    }
   
    public Rejilla getRejilla(){
        return rejilla;
    }
    
    public Figura getComecocos(){
        return comecocos;
    }
    
     public Figura[] getFantasmas(){
        return fantasmas;
    }
     
     public void setDireccionFantasma(int i, int direccion){
         fantasmas[i].setDireccion(direccion);
         fantasmas[i].mueve(direccion);
     }
     
     public boolean azules(){
         return azules;
     }
     
     public void setAzules(){
        azules = true;
        this.timer.cancel(); 
        this.timer = new Timer();

        TimerTask action = new TimerTask() {
            public void run() {
                azules = false;
            }

        };

        this.timer.schedule(action, 10000); //this starts the task
    }
     
    public void muerto(){
        comecocos.setI(1);
        comecocos.setJ(14);
        comecocos.setDireccion(1);
        getPanel().setParpadeo();
        
        vidas--;
        gestionaVidas();
    }
    
    public void gestionaVidas(){
        if(vidas == 2){
            vida3.setVisible(false);
        }
        else if (vidas == 1){
            vida3.setVisible(false);
            vida2.setVisible(false);
        }
        else if (vidas == 0){
            vida3.setVisible(false);
            vida2.setVisible(false);
            vida1.setVisible(false);
            
            mueve.terminar();
            gameover.setVisible(true);
            //MUERTO
        }
    }
     
    
    public void init(){
        
        comecocos = new Figura(26,14,1);
        int pos = 12;
        int posy = 13;
        for(int i=0;i<nFantasmas;i++){
            if(pos == 15){
                pos = 12;
                posy = 15;
            }
            fantasmas[i]= new Figura(pos,posy,0);
            pos++;
        }
        mueve = new Mueve(this);
        if(mueve!=null && !mueve.getTerminado())
            mueve.terminar();
        
        mueve=new Mueve(this);
        
        Thread t=new Thread(mueve);
        t.start();
        mueve.reanudar();
    }
    
    public RejillaPanel getPanel(){
        return rejillaPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        vida1 = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        vida3 = new javax.swing.JLabel();
        rejillaPanel1 = new RejillaPanel(this);
        gameover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(430, 580));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        label1.setText("VIDAS:");

        vida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vida.png"))); // NOI18N

        vida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vida.png"))); // NOI18N

        vida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vida.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vida2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vida1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vida3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vida2)
                    .addComponent(vida1)
                    .addComponent(vida3)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(517, Short.MAX_VALUE))
        );

        rejillaPanel1.setMinimumSize(new java.awt.Dimension(28, 31));

        gameover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gameover.png"))); // NOI18N

        javax.swing.GroupLayout rejillaPanel1Layout = new javax.swing.GroupLayout(rejillaPanel1);
        rejillaPanel1.setLayout(rejillaPanel1Layout);
        rejillaPanel1Layout.setHorizontalGroup(
            rejillaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rejillaPanel1Layout.createSequentialGroup()
                .addComponent(gameover)
                .addGap(0, 226, Short.MAX_VALUE))
        );
        rejillaPanel1Layout.setVerticalGroup(
            rejillaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rejillaPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(gameover)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rejillaPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rejillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComecocosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameover;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private comecocos.RejillaPanel rejillaPanel1;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    private javax.swing.JLabel vida3;
    // End of variables declaration//GEN-END:variables
}
